### ISSUE TITLE
Integration stopped working - "Invalid credentials"

### ISSUE THREAD

**Issue by W-Floyd** [ryanmac8/HA-Mint-Mobile#13]
**Describe the bug**
The integration fails to authenticate

**To Reproduce**
1. Add the Mint Mobile integration.
2. Enter credentials
3. Click submit
4. See "Invalid credentials" error

**Expected behavior**
The integrations works

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The integration was working correctly, then failed to update sensors. Attempting to re-add the integration yields the error.

**Comment by ryanmac8** [comment]
@W-Floyd I know Mint Mobile has been down the last few days. Currently, I am not able to login to the Mint Mobile website, thus the API isn't working at the moment.

Are you able to login to the Mint Mobile website?
![mintmobileerror](https://user-images.githubusercontent.com/7333067/121749904-708dfe80-cad9-11eb-86c1-d0762d62014f.JPG)

**Comment by W-Floyd** [comment]
Yes, I am able to log into the website.

**Comment by ryanmac8** [comment]
Strange. I'm still getting an error page. I wonder if they made some changes to their API. Let me do some more testing to see if I can figure out what's going on.

**Comment by ryanmac8** [comment]
Looks like they have updated their security a few days ago and this is affecting our integration.
https://www.reddit.com/r/mintmobile/comments/nvkz83/users_experiencing_reset_password_notifications/

**Comment by ryanmac8** [comment]
Updated the API. Seems to be working now with version 1.7
