### ISSUE TITLE
Doesn't seem to work with 

### ISSUE THREAD

**Issue by spencerthayer** [ryanmac8/HA-Mint-Mobile#16]
Doesn't seem to work with core-2021.11.2 supervisor-2021.10.8. Can't add it as a card. No where to be found.

**Comment by ryanmac8** [comment]
@spencerthayer I'm on core-2021.11.2 and it seems to be working fine. Have you added it via HACS or the custom component folder? Also what do you mean by can't add it as a card? There's no front end card to add. It just creates the sensors and populates the data.
