### ISSUE TITLE
Entity implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by nholben** [ryanmac8/HA-Mint-Mobile#17]
**Describe the bug**
Warning message on start up - Entity x.x implements device_state_attributes. Please report it to the custom component author.

**To Reproduce**
1. Start/Restart HA Core
2. Check logs
4. See warning

**Expected behavior**
No warnings.

**Screenshots**
Entity sensor.morgan_mint_mobile_days_remaining_in_month (<class 'custom_components.mintmobile.sensor.DaysRemainingInMonthSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.nathan_mint_mobile_days_remaining_in_month (<class 'custom_components.mintmobile.sensor.DaysRemainingInMonthSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.morgan_mint_mobile_days_remaining_in_plan (<class 'custom_components.mintmobile.sensor.DaysRemainingInPlanSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.morgan_mobile_data_usage_remaining (<class 'custom_components.mintmobile.sensor.MintMobileSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.nathan_mint_mobile_plan_term (<class 'custom_components.mintmobile.sensor.CurrentPlanSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Additional context**
HA Supervised 2021.12.9
Mint Mobile Integration via HACS v1.8

**Comment by ryanmac8** [comment]
@nholben Thanks for reporting. I'll take a look and push out a change to address that.

**Comment by ryanmac8** [comment]
@nholben Pushed out v1.9 to fix issue. Please upgrade and that error message should no longer be present.

**Comment by nholben** [comment]
Fixed - Thank you!
