### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [ryanmac8/HA-Mint-Mobile#2]
*Sorry for not following the issue template*

If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by ryanmac8** [comment]
Sure. Feel free to submit a PR.

**Comment by KTibow** [comment]
Mind answering some of the questions in the bullet points?

**Comment by ryanmac8** [comment]
My bad. Auto formatting is fine. I'm not sure what the difference between packaged and independent is.

**Comment by KTibow** [comment]
I'll send in a PR.
