### ISSUE TITLE
Some entities missing from integration

### ISSUE THREAD

**Issue by johnsturgeon** [ryanmac8/HA-Mint-Mobile#22]
**Describe the bug**
Some sensors not being created

I have four users on my plan, and only two of them have 'all' their data, two of them don't show the data used data remaining

Here is a log entry I'm getting

```
Logger: homeassistant.components.sensor
Source: custom_components/mintmobile/sensor.py:211 
Integration: Sensor (documentation, issues) 
First occurred: May 14, 2022, 10:36:46 AM (7 occurrences) 
Last logged: 8:47:51 AM

mintmobile: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/mintmobile/sensor.py", line 211, in async_update
    if isinstance(self.data["used4G"], numbers.Real):
KeyError: 'used4G'
```

**Comment by ryanmac8** [comment]
@johnsturgeon the integration seems to be working for me. Are you still having issues?
Also, for the two lines that don't show data, have you tried manually adding those lines in a separate integration to see if they work?

**Comment by johnsturgeon** [comment]
This is a good idea to try.  When I have a chance (I'm currently on a small holiday) I'll give it a try, let's keep this open until I do.

I can also try and reproduce the issue with the repo locally on my Mac, and get the detailed json and figure out what's different in the data that the code isn't seeing.

**Comment by johnsturgeon** [comment]
I was able to add the other two accounts as individual integrations, so all is good.

**Comment by ryanmac8** [comment]
Alright. That's good to hear at least. If you do want to dig deeper and see what's going on with the integration, there's a test.py file that can be run to output all the json data.
