### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by Ali229** [ryanmac8/HA-Mint-Mobile#23]
**Describe the bug**
This morning it shows: Entity is currently unavailable. Before today it used to work perfectly.

**Expected behavior**
Show entity.

**Comment by ryanmac8** [comment]
@Ali229 Mint Mobile is currently down at the moment so that's why it's not working.

**Comment by Ali229** [comment]
@ryanmac8 Do you mean the API is down?

**Comment by ryanmac8** [comment]
Yes. Their whole mobile app and api's were not working yesterday when I checked. They often go into maintenance mode, which breaks all API communications.

**Comment by Ali229** [comment]
Integration has started working again.
