### ISSUE TITLE
manifest.json pins python requests version at 2.22.0

### ISSUE THREAD

**Issue by montaguk** [ryanmac8/HA-Mint-Mobile#6]
**Describe the bug**
Not compatible with newer versions of python requests library.

**To Reproduce**
Try to install/configure the plugin on a HA installation with newer version of python requests lib. In the HA log, there will be an error message complaining about the wrong version of requests.

**Expected behavior**
Installation should succeed. See notes below

**Additional context**
Installed component via HACS on a ubnutu-based install of HA. Currently have version 2.25.0 of python requests lib. Manually adjusting the manifest as shown below seems to have made everything happy.
```
  "requirements": ["requests>=2.22.0"],
```

I forked the repo and can submit a PR if you'd like, but it's such a simple change it might just be easier to fix it on your next set of changes.

**Comment by ryanmac8** [comment]
I can update it tonight as I got another bug fix I'm working on.

**Comment by montaguk** [comment]
Sweet! Thanks for the quick reply, and the handy component!

**Comment by ryanmac8** [comment]
@montaguk Just released v1.4 that fixes this issue.
