### ISSUE TITLE
Please break the attributes into additional sensors

### ISSUE THREAD

**Issue by mercplus** [ryanmac8/HA-Mint-Mobile#9]
**Is your feature request related to a problem? Please describe.**
Have to create additional attribute sensors manually for each family line today

**Describe the solution you'd like**
Break the attribute into additional sensors, to help with automations

**Describe alternatives you've considered**
It's quite cumbersome to manually add attribute as sensors especially when we have family added to the plan

**Additional context**

**Comment by ryanmac8** [comment]
@mercplus which attributes do you need broken out? Can you be specific so I can ensure the ones you want are created.

**Comment by mercplus** [comment]
@ryanmac8 these would be great - 

Days remaining in the month
Days remaining in the plan
Current plan term

**Comment by ryanmac8** [comment]
@mercplus Upgrade to v1.5. Under the options setting for the integration, you can enable the creation of additional sensors from attributes.
